### ISSUE TITLE
FunctionNode variables created but are not functions

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.model.neuroml#103]
https://github.com/openworm/org.geppetto.model.neuroml/blob/html_variables/src/main/java/org/gepppetto/model/neuroml/summaryUtils/PopulateSummaryNodesUtils.java#L517

Some variables are created with expressions like this :
org.neuroml.export.info.model.HHVariableToIHHExpressionAdapter@29f4f343
These the plotting widget can't plot.
The ones that are being plotted are in this form: 1E2 * (v - (-2.6E-2))/1E-2 / ( 1 - exp(-(v - (-2.6E-2)) / 1E-2))

The expressions are being returned from the org.neuroml.export jar.

**Comment by jrmartin** [comment]
@tarelli @adrianq This is the issue with Function Nodes being created that aren't functions.

**Comment by adrianq** [comment]
@jrmartin The export library does not provide expressions for every single channel. This is the expected behaviour. I remembered to add a validation some time ago (but maybe it was on the OSB side) in order to check if it was a proper equation or just an string like "org.neuroml.export..."

**Comment by jrmartin** [comment]
@adrianq I'm testing it using the Golgi example, and it creates a FunctionPlot object for variable : "Model.neuroml.Golgi_hcn1f.f.f.steadyState.steadyState.steady_state_" in the method I posted above. When the function is retrieved in the Plot.js it comes this way: 
"f(v) =org.neuroml.export.info.model.HHVariableToIHHExpressionAdapter@11f98f36"which the Plot can't do much with.

**Comment by jrmartin** [comment]
I added the if statement on the branch I'm working on to avoid adding those variables that start with org.neuroml as plottable ones, takes care of the issue
