### ISSUE TITLE
combine resources

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.model.neuroml#110]
[Resources.java](https://github.com/openworm/org.geppetto.model.neuroml/blob/master/src/main/java/org/geppetto/model/neuroml/utils/Resources.java) and 
[ResourcesDomainType.java](https://github.com/openworm/org.geppetto.model.neuroml/blob/master/src/main/java/org/geppetto/model/neuroml/utils/ResourcesDomainType.java) seem to be needless duplicates?

**Comment by tarelli** [comment]
@adrianq any reason for the split that you can remember?

**Comment by adrianq** [comment]
Yes, there is a reason. They are used for two different purposes as far as I remember. ResourcesDomainType is used to generate the description node (summary which is displayed on a pop up widget when a model is opened on OSB). It is used to group different elements: network, cells, channels, etc. However, Resources is used to get a nice label for every single NeuroML component. It is used in the Treevisualiser, in the summary aforementioned, etc. Also, methods at the bottom of the class are different as they have different purposes. Comments at the top of the class are the same but this is a bug, probably a dirty copy&paste.

I preferred not to merge the two classes as, IMO, it would make everything a little bit messy and less handy. Maybe, after having a deep look at where and how this Enum are used, I would rename classes, comment it better and perform any minor refactor if needed...

**Comment by tarelli** [comment]
@mattearnshaw can we close this?
