### ISSUE TITLE
Species should attach to all segments when no group species

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.model.neuroml#113]
see for example at https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/cells/I2L_D.cell.nml#L194

there should be potential instances of caConc on all the segments in Geppetto eg. at http://opensourcebrain.org/projects/celegans?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Ftemp_test%252Fc302_D_Pharyngeal.net.nml#

**Comment by tarelli** [comment]
@mattearnshaw can you add more details to what you would expect to see? NeuroML is declaring those parameters at the cell level, what do you mean on all segments? The only two things extracted at the segment level on multi-compartment models are two state variables "spiking" and "v".
<img width="1485" alt="screen shot 2017-01-27 at 17 27 49" src="https://cloud.githubusercontent.com/assets/81127/22380622/fffd5610-e4b5-11e6-8fee-3a06df587a40.png">

**Comment by mattearnshaw** [comment]
eg. we would expect 641 potential instances ending `caConc` with the above model, the same number as for `spiking` and `v`. <species> is at the cell level but it has an optional segmentGroup attr. @pgleeson may clarify further

**Comment by tarelli** [comment]
I think I understand what you mean now, @pgleeson will remember last time we discussed this he decided to expose only two variables for multi-compartment models, v and spiking. We could add caConc too I think but need to look into it more if that's the case.

**Comment by pgleeson** [comment]
Yes, @tarelli, that was fine as a default option, since it's a good assumption that v (and therefore spiking) will be present on all segments. However, to determine where [Ca2+] is present, it will be necessary for the NeuroMLModelInterpreter to look in detail at the the nml, e.g. 


                <channelDensity condDensity="10.0 mS_per_cm2" id="Ca_pyr_soma_group" ionChannel="Ca_pyr" segmentGroup="soma_group" ion="ca" erev="80.0 mV"/>
                ...
                <species segmentGroup="soma_group" id="ca" ion="ca" concentrationModel="Ca_conc" initialConcentration="5.0E-11 mol_per_cm3" initialExtConcentration="3.0E-6 mol_per_cm3"/>

and figure out which state variables related to which concentrationModel/ionChannel etc. should be recordable on which segments.

**Comment by tarelli** [comment]
@pgleeson makes sense 👍

**Comment by mattearnshaw** [comment]
in progress here https://github.com/openworm/org.geppetto.model.neuroml/commit/56d279e91a7c86a2bd711b6a77f253b6ebad2e46. it's not looking at segmentGroup yet, but does expose only when `<species>` is present

**Comment by mattearnshaw** [comment]
(in `calcium` branch)
