### ISSUE TITLE
Double check neuroml extraction in PopulateNeuroMLModelTree

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.model.neuroml#48]

**Comment by tarelli** [comment]
@adrianq see also what @pgleeson spotted yesterday for erev vs reversepotential

**Comment by adrianq** [comment]
@tarelli Do you think we should parse input types in neuroml document? See https://github.com/NeuroML/NeuroML2/blob/master/Schemas/NeuroML2/NeuroML_v2beta3.xsd#L396

**Comment by adrianq** [comment]
Some work has been done but there are more things to improve (See list above). Move to "TO DO" until I have some spare time

**Comment by pgleeson** [comment]
Think once there's progress with https://github.com/OpenSourceBrain/redmine/issues/146 it will be much easier to see what is and what isn't accessible from the model.

**Comment by tarelli** [comment]
@adrianq can you update this when you get a chance?

**Comment by adrianq** [comment]
@tarelli Let me finish with the treevisualsier work and I will update/close the issue accordingly.
