### ISSUE TITLE
Missing geometries in muscle model

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.model.neuroml#51]
The [simulation](https://live.geppetto.org/?sim=https://raw.githubusercontent.com/dkruchinin/org.geppetto.samples/muscle_model/LEMS/MuscleModel/GEPPETTO.xml) should show one sphere for the IAF cell and one cylinder for the muscle model but they are not showing.

**Comment by tarelli** [comment]
Did some fixes as part of this now the cylinder of the muscle shows in the head of development, however the network is not picked up because it is declared in Lems and support for that is currently missing. cc @adrianq

**Comment by tarelli** [comment]
This is blocked now by https://github.com/openworm/org.geppetto.model.neuroml/issues/52.
Even once that will be fixed we still need to split the network outside of LEMS and into a NML file if we want it to be visualized. LEMS doesn't know what a network is, what a projection is or what any of the components are. Their syntax is defined but that is all. Network might as well be called "horse" but that wouldn't entitle us to paint a horse in Geppetto. To know what a Network is we need to know that it is a NeruoML model which is something that we can infer from the extension of the include although this is not elegant. Ideally you would want to read the header that says <NeuroML> but those are getting stripped out at the moment since they would create a problem inside LEMS since LEMS knows nothing about NeuroML. @pgleeson if you agree with the above while we take care of the other bug could the network be moved inside its own NeuroML file?

**Comment by pgleeson** [comment]
I've added a separate nml2 file for the neuron&muscle now. It can be visualized:

![selection_603](https://cloud.githubusercontent.com/assets/1556687/5840475/c9264d8a-a18d-11e4-9696-ad2e5c4452f7.jpg)

but one of the cells is missing. Also, the SingleCompMuscle.cell.nml fails to visualise on its own:

![selection_604](https://cloud.githubusercontent.com/assets/1556687/5840504/f2275044-a18d-11e4-96fd-b545f540073f.jpg)

**Comment by tarelli** [comment]
@pgleeson Thanks! Are you using the live deployment or the latest dev environment? I did already some fixes. Anyway there is work related to https://github.com/openworm/org.geppetto.model.neuroml/issues/52 still before closing this off.

**Comment by pgleeson** [comment]
Testing on OSB...

**Comment by pgleeson** [comment]
I've noticed some strange behaviour with mapping the [SingleCompMuscle.cell.nml](https://github.com/openworm/muscle_model/blob/master/NeuroML2/SingleCompMuscle.cell.nml) to other formats which was down to the lack of any `<segmentGroup>` element in the cell. Your viz could be failing if it finds no segmentGroups here too. 

Normally the groups are there for identifying soma_group, axon_group etc. It's still a valid cell without segmentGroups so this case should be supported too...
