### ISSUE TITLE
Fix visualization for LEMS/NeuroML nested models

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.model.neuroml#52]
At the moment if a LEMS file is specified inside a simulation we process all the includes that are NeuroML files and we visualise them. This is wrong. Whether something is included or not should be completely irrelevant for visualisation purposes. We should instead start from the <Target> element in a LEMS file (and if that doesn't exist nothing is visualised).
See for instance https://raw.githubusercontent.com/dkruchinin/org.geppetto.samples/muscle_model/LEMS/MuscleModel/LEMS_NeuronMuscle.xml
We should start from the following
```<Target component="sim1"/>```  which would lead us to net1 where we are defining an integrate and fire cell, a muscle cell and a connection between them.

**Comment by adrianq** [comment]
The model pointed in this card is not going to work as the network is defined in the lems file and it should be defined in the neuroml file. However we have implemented the bit of code that looks for the target component and visualise only the components pointed by it. See for instance: https://raw.githubusercontent.com/openworm/org.geppetto.samples/development/LEMS/MuscleModel/LEMS_NeuronMuscle.xml

If none target component is specified every geometry finds in the model will be visualised inside Geppetto.
