### ISSUE TITLE
"Rich" mathematical expression handling

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.model.neuroml#62]
Mathematical expressions in NeuroML / LEMS models are currently interpreted as plain strings. We would like them to be plottable (i.e. mapped to geppetto function nodes), and to be nicely typeset (MathML).

Currently, the only way to "resolve" expressions (i.e. map symbols to other expressions etc) is feeding them to jLEMS - which will build a "runnable" instance of the model -- and digging into the jLEMS api for each one of the symbols).

 The new LEMS parser (not quite ready yet) [org.lemsml.model](https://github.com/tarelli/org.lemsml.model) will have expression evaluation capabilities (no need to use jLEMS for parsing a LEMS model) is a good backend candidate, as it can fully resolve variables / parameters and (well, will in the future) generate evaluable objects, as well as exporting them to arbitrary formats (e.g. MathML, see [here](https://github.com/borismarin/expr-parser/blob/master/src/main/java/expr_parser/parser/AdaptToLatexVisitor.java).

Not sure how long it will take to have org.lemsml.model in a usable state, but let's try a to-do list:
- [ ] have org.lemsml.model generate "evaluable" expressions (implements IEvaluable: has an "eval(...)" method, and  also a listIndependentVariables() method as functions can be multivariate)
- [ ] add org.lemsml.model as a dependency in org.geppetto.model.neuroml
- [ ] map all IEvaluable implementers to geppetto function nodes
- [ ] make the tree visualizer widget render mathml for function nodes

Notice that, in the future, org.lemsml.model will also be able to [expose domain-specific APIs](https://github.com/tarelli/org.lemsml.model/issues/28) (and also [here](https://github.com/borismarin/org.neuroml2.model)), so this will allow us to fully replace ad-hoc jLEMS calls in org.geppetto.model.neuroml .

**Comment by tarelli** [comment]
@borismarin I would allocate 40 story points to this one excluding the last bullet point for which it might be another 13/20 (layout can be painful).

**Comment by borismarin** [comment]
I have no idea about the exchange rate between points and difficulty, so go ahead and assign as many as you want.

**Comment by tarelli** [comment]
1 point = 1 hour

**Comment by borismarin** [comment]
Whose hours =) ?

**Comment by tarelli** [comment]
Someone familiar with all the concepts and libraries involved and with
experience both on backend and frontend coding, e.g. you.
ᐧ

On 8 April 2015 at 12:52, Boris Marin <notifications@github.com> wrote:

> Whose hours =) ?
>
> On 8 April 2015 at 12:51, Matteo Cantarelli <notifications@github.com>
> wrote:
>
> > 1 point = 1 hour
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openworm/org.geppetto.model.neuroml/issues/62#issuecomment-90889975
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openworm/org.geppetto.model.neuroml/issues/62#issuecomment-90890141>
> .
>



-- 
Matteo Cantarelli

email: matteo.cantarelli@gmail.com
mobile : +44 (0)74 47540306
skype: tarelli1138
http://it.linkedin.com/in/matteocantarelli

**Comment by borismarin** [comment]
You hold me in high esteem, thanks.

**Comment by borismarin** [comment]
Working on the first point, will take a while since it boils down to writing a LEMS compiler!

**Comment by borismarin** [comment]
Not geppetto specific. See https://github.com/borismarin/neuroml2model https://github.com/borismarin/org.lemsml.model

**Comment by LordKrabo** [comment]
Hey @borismarin Can I assign this to sprint 74? Cheers

**Comment by tarelli** [comment]
@LordKrabo Thanks for the ping! For the cards in "ideas" we were using the "Assigned" field for whoever came up with the idea rather than who was going to do it. As for this one in particular I'm going to close it since it's not geppetto specific in its current formulation.

**Comment by borismarin** [comment]
Hello @LordKrabo, thanks for the reminder. The tasks on this card are outdated (mainly due to the instance/type refactoring). I'll have a chat with @adrianq and @tarelli later next week, and then update the action points.
