### ISSUE TITLE
Domain specific info on NeuroML model tree

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.model.neuroml#63]
In order to provide (domain specific) "type" based functionality (e.g., for specific case of NeuroML, we would like to do some things to "cells", and some other things to "networks") we need to decorate the generated model tree with more domain specific knowledge, and also be able to retrieve this information easily.

In particular, [we are already doing that for synapses](https://github.com/openworm/org.geppetto.model.neuroml/blob/development/src/main/java/org/geppetto/model/neuroml/services/NeuroMLModelInterpreterService.java#L406), and this information will (openworm/org.geppetto.frontend#238) be used to generate connections in the Connectivity Widget. 

This will basically involve a lot of manual logic (as the user can always come up with new NeuroML entities that "represent" (implement?) e.g. a "cell").

We will then need an API to get all nodes that have a specific Domain Type.

TODO:
- [x] Mark all cells in the NeuroML schema as "ResourcesDomainType.CELL"([here](https://github.com/openworm/org.geppetto.model.neuroml/blob/master/src/main/java/org/geppetto/model/neuroml/utils/modeltree/PopulateNeuroMLModelTreeUtils.java#L205)) 
- [x] Mark all channels in the NeuroML schema as "ResourcesDomainType.IONCHANNEL"
- [x] Mark all networks in the NeuroML schema as "ResourcesDomainType.NETWORK"
- [x] Mark all synapses in the NeuroML schema as "ResourcesDomainType.SYNAPSE"
- [x] update the [ResourceDomainType](https://github.com/openworm/org.geppetto.model.neuroml/blob/development/src/main/java/org/geppetto/model/neuroml/utils/ResourcesDomainType.java) enum 
- [x] write a method _getNodesByDomainType(aResourceDomainType)_ which will return a list of nodes with that type.

This functionality can then be used by "domain-aware" widgets like the connectivity widget, the tree view, the [control panel](opensourcebrain/redmine#146).

**Comment by tarelli** [comment]
@adrianq @borismarin to merge this we first need to merge development into it

**Comment by borismarin** [comment]
It's @adrianq 's fault. Will check with him.

**Comment by borismarin** [comment]
Done
