### ISSUE TITLE
Update org.neuroml.model.jar with the latest version

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.model.neuroml#71]
Currently we are missing some information from the neuroml models such as notes

- [x] Update jLEMS
- [x] Update org.neuroml.model
- [x] Update org.neuroml.export

**Comment by tarelli** [comment]
@adrianq the latest in master?

**Comment by adrianq** [comment]
I guess from development. Master has a very old version 1.3.1... I have checked [geppetto maven repo] (https://github.com/openworm/org.geppetto.maven/tree/mvn-repo/org/neuroml/model/org.neuroml.model) and we do have 1.4.2 but we are using 1.4.0 in org.geppetto.model.neuroml

**Comment by tarelli** [comment]
Does 1.4.2 have what you want? Let me know if there is a new JAR to be deployed.

**Comment by adrianq** [comment]
I just want a bottle of red wine, some jamon serrano and Bob Marley singing for me but in the meantime I will have a look at the 1.4.2 and let you know... cheers!

**Comment by tarelli** [comment]
https://twitter.com/tarelli/status/596386435525120000

**Comment by adrianq** [comment]
:) @pgleeson suggests to release the latest from org.neuroml.model (the jar we have in Geppetto was created two months ago but there are some recent changes). Obviously we have to test it properly before including it in a release. Bottom line, I think we can postpone this update for June release. Assigning it to me

**Comment by tarelli** [comment]
Sounds wise +1

**Comment by adrianq** [comment]
@pgleeson I would like to update the libs (jLEMS, neuroml.model and neuroml.export) for this release. Shall I use the development branches? Is everything there and is it stable enough?

**Comment by pgleeson** [comment]
Yes, I tested them a day or two ago with all OMV projects. Grab them now...
