### ISSUE TITLE
Polish NeuroML Summary and make it available in the treevisualiser and samples

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.model.neuroml#83]
Create anchor element with an instancePath attribute

**Comment by adrianq** [comment]
This is done but it will have to be polished once the instance/type refactor is done. Moving it to 'To do' column for the moment

**Comment by tarelli** [comment]
@adrianq let's check this again after the current tree visualizer work is done

**Comment by adrianq** [comment]
@tarelli Yes, I want to do it this week. Keep you updated!
